application: simple-go-cms
version: 1
runtime: go
api_version: 3

handlers:
- url: /_config
  login: admin
  script: _go_app

- url: /_.*
  login: required
  script: _go_app

- url: /.*
  script: _go_app
