application: simple-go-cms
version: 1
runtime: go
api_version: go1beta

handlers:
- url: /_(config|saveconfig)
  login: admin
  script: _go_app

- url: /_.*
  login: required
  script: _go_app

- url: /.*
  script: _go_app
